version: "3.9"
services:
  build:
    build: .
    image: tinygo/tinygo:0.27.0
    volumes:
      - .:/app
    environment:
      - TARGET=${TARGET}
      - TAGS=${TAGS}
      - GOFLAGS=-buildvcs=false
    command: sh -xc "go mod tidy && mkdir -p build && tinygo build -tags '${TAGS}' -target ${TARGET:-pico} -o build/diy-ffb-wheel.uf2 ."
    working_dir: /app
    tty: true
