version: "3.9"
services:
  build:
    build: .
    image: tinygo/tinygo:0.27.0
    volumes:
      - .:/app
    environment:
      - OPTIONS=${OPTIONS}
    command: sh -c 'go mod tidy && mkdir -p build && GOFLAGS="-buildvcs=false" tinygo build $${OPTIONS:--target pico} -o build/diy-ffb-wheel.uf2 .'
    working_dir: /app
    tty: true
